### PR TITLE
Event modifications

### LINKED ISSUE #60: stepchange event
I noticed the `stepchange` event was not being fired when clicking on title linkes.

Moving/adding "stepper.dispatchEvent(events.STEPCHANGE);" from `openStep`, `nextStep`, `prevStep` and into `_openAction` fixed the issue.

### PR DESCRIPTION
**Pull request by brianpkelley**
Added "stepopen", "stepclose", and moved "stepchange", as well as updated the docs and added new "Events" Demo section
Fixes #60

### CODE REVIEW

**Comment by Kinark** [comment]
Hey, @brianpkelley!
Thanks you for the PR :)

But could you please move the changes made in `src/html_docs/components/scripts.html` file to `src/html_docs/components/sections/components/api/components/events.html` file?

**Comment by Kinark** [comment]
Just fixed what I needed to fix.
Thanks for the PR! :D

I'm merging it right now and releasing a version real soon.

**Comment by Kinark** [comment]
#60 Fixed

**Comment by brianpkelley** [comment]
Ah sorry, my family and I are right in the middle of a move, glad I could help out!

**Pull request merged**
